name: Rust-Mac

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run build release
      run: cargo build --release --verbose
    - name: install youtube-dl
      run: brew install youtube-dl
    - name: get-the video
      run: youtube-dl https://www.youtube.com/watch?v=1vvyyhteIv4
    - name: list-files
      run: ls -al .
    - name: Upload a Build Artifact udp-client
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: udp-client
        path: target/release/udp-client 
        warn: Output a warning but do not fail the action
    - name: Upload a Build Artifact udp-server
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: udp-server
        path: target/release/udp-server
        warn: Output a warning but do not fail the action
