name: Rust-linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run build release
      run: cargo build --release --verbose
    - name: Upload a Build Artifact client
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: client
        path: target/release/udp-client
        warn: Output a warning but do not fail the action 
    - name: Upload a Build Artifact server
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: server
        path: target/release/udp-server
        warn: Output a warning but do not fail the action 
